CREATE TABLE reservation_slots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slot_date DATE NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  capacity INT NOT NULL DEFAULT 3,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_reservation_slots_date_time UNIQUE (slot_date, start_time),
  CONSTRAINT chk_reservation_slots_capacity CHECK (capacity >= 0),
  CONSTRAINT chk_reservation_slots_time CHECK (start_time < end_time)
);

CREATE TABLE reservations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reservation_code VARCHAR(20) NOT NULL,
  reservation_slot_id BIGINT NOT NULL,
  patient_name VARCHAR(50) NOT NULL,
  patient_kana VARCHAR(50) NOT NULL,
  birth_date DATE NOT NULL,
  phone_number VARCHAR(20) NOT NULL,
  email VARCHAR(255),
  visit_type VARCHAR(20) NOT NULL,
  symptom VARCHAR(500),
  status VARCHAR(20) NOT NULL DEFAULT 'RESERVED',
  cancel_reason VARCHAR(30),
  agreed_to_privacy_policy BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_reservations_reservation_code UNIQUE (reservation_code),
  CONSTRAINT fk_reservations_reservation_slot
    FOREIGN KEY (reservation_slot_id)
    REFERENCES reservation_slots (id),
  CONSTRAINT chk_reservations_visit_type
    CHECK (visit_type IN ('FIRST', 'RETURN')),
  CONSTRAINT chk_reservations_status
    CHECK (status IN ('RESERVED', 'CANCELLED', 'VISITED')),
  CONSTRAINT chk_reservations_cancel_reason
    CHECK (cancel_reason IS NULL OR cancel_reason IN ('PATIENT_REQUEST', 'CLINIC_REASON', 'DUPLICATE', 'OTHER')),
  CONSTRAINT chk_reservations_privacy_policy
    CHECK (agreed_to_privacy_policy = TRUE)
);

CREATE INDEX idx_reservations_slot_status
  ON reservations (reservation_slot_id, status);

CREATE INDEX idx_reservations_status
  ON reservations (status);
